### ISSUE TITLE
Problem in configuring

### ISSUE THREAD

**Issue by sikkaka** [Netflix/dynomite-manager#81]
Hi,
As we are planning to move from redis sentinel to dynomite.I try to configure DM to local datacenters, i'm facing these issuses even i have implemented floridaconfig. Can anyone guide me to configure

`./gradlew jettyrun
Inferred project: dynomitemanager, version: 2.1.0-SNAPSHOT
Publication nebula not found in project :.
Publication named 'nebula' does not exist for project ':' in task ':artifactoryPublish'.
:dynomitemanager-web:prepareInplaceWebAppFolder UP-TO-DATE
:dynomitemanager-web:createInplaceWebAppFolder UP-TO-DATE
:dynomitemanager-common:compileJava UP-TO-DATE
:dynomitemanager-common:processResources NO-SOURCE
:dynomitemanager-common:classes UP-TO-DATE
:dynomitemanager-common:writeManifestProperties UP-TO-DATE
:dynomitemanager-common:jar UP-TO-DATE
:dynomitemanager-core:compileJava UP-TO-DATE
:dynomitemanager-core:processResources NO-SOURCE
:dynomitemanager-core:classes UP-TO-DATE
:dynomitemanager-core:writeManifestProperties UP-TO-DATE
:dynomitemanager-core:jar UP-TO-DATE
:dynomitemanager-web:compileJava UP-TO-DATE
:dynomitemanager-web:processResources UP-TO-DATE
:dynomitemanager-web:classes UP-TO-DATE
:dynomitemanager-web:prepareInplaceWebAppClasses UP-TO-DATE
:dynomitemanager-web:prepareInplaceWebApp UP-TO-DATE
:dynomitemanager-web:jettyRun
log4j:WARN No appenders could be found for logger (com.netflix.governator.LifecycleManager).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
15:52:59 WARN  Failed startup of context o.a.g.JettyWebAppContext@1a6c1270{/,file:/$HOME/dynomite-manager/dynomitemanager-web/build/inplaceWebapp/,STARTING}
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Failed to create injector

1 error
        at com.netflix.governator.guice.servlet.GovernatorServletContextListener.getInjector(GovernatorServletContextListener.java:111) ~[na:na]
        at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:47) ~[na:na]
        at com.netflix.governator.guice.servlet.GovernatorServletContextListener.contextInitialized(GovernatorServletContextListener.java:86) ~[na:na]
        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:800) ~[jetty-server-9.2.22.v20170606.jar:9.2.22.v20170606]
        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:444) ~[jetty-servlet-9.2.22.v20170606.jar:9.2.22.v20170606]
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:791) ~[jetty-server-9.2.22.v20170606.jar:9.2.22.v20170606]
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:294) ~[jetty-servlet-9.2.22.v20170606.jar:9.2.22.v20170606]
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349) ~[jetty-webapp-9.2.22.v20170606.jar:9.2.22.v20170606]
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342) ~[jetty-webapp-9.2.22.v20170606.jar:9.2.22.v20170606]
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741) ~[jetty-server-9.2.22.v20170606.jar:9.2.22.v20170606]
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505) ~[jetty-webapp-9.2.22.v20170606.jar:9.2.22.v20170606]
        at org.akhikhl.gretty.JettyWebAppContext.super$10$doStart(JettyWebAppContext.groovy) [gretty-runner-jetty9-2.0.0.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_112]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_112]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_112]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_112]
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93) [groovy-2.4.11.jar:2.4.11]
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325) [groovy-2.4.11.jar:2.4.11]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213) [groovy-2.4.11.jar:2.4.11]
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:132) [groovy-2.4.11.jar:2.4.11]
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:152) [groovy-2.4.11.jar:2.4.11]
        at org.akhikhl.gretty.JettyWebAppContext.doStart(JettyWebAppContext.groovy:44) [gretty-runner-jetty9-2.0.0.jar:na]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.2.22.v20170606.jar:9.2.22.v20170606]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132) [jetty-util-9.2.22.v20170606.jar:9.2.22.v20170606]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114) [jetty-util-9.2.22.v20170606.jar:9.2.22.v20170606]
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61) [jetty-server-9.2.22.v20170606.jar:9.2.22.v20170606]
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:163) [jetty-server-9.2.22.v20170606.jar:9.2.22.v20170606]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.2.22.v20170606.jar:9.2.22.v20170606]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132) [jetty-util-9.2.22.v20170606.jar:9.2.22.v20170606]
        at org.eclipse.jetty.server.Server.start(Server.java:387) [jetty-server-9.2.22.v20170606.jar:9.2.22.v20170606]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114) [jetty-util-9.2.22.v20170606.jar:9.2.22.v20170606]
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61) [jetty-server-9.2.22.v20170606.jar:9.2.22.v20170606]
        at org.eclipse.jetty.server.Server.doStart(Server.java:354) [jetty-server-9.2.22.v20170606.jar:9.2.22.v20170606]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.2.22.v20170606.jar:9.2.22.v20170606]
        at org.eclipse.jetty.util.component.LifeCycle$start$0.call(Unknown Source) [jetty-util-9.2.22.v20170606.jar:9.2.22.v20170606]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) [groovy-2.4.11.jar:2.4.11]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) [groovy-2.4.11.jar:2.4.11]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117) [groovy-2.4.11.jar:2.4.11]
        at org.akhikhl.gretty.JettyServerManager.startServer(JettyServerManager.groovy:45) [gretty-runner-jetty-2.0.0.jar:na]
        at org.akhikhl.gretty.ServerManager$startServer$0.call(Unknown Source) [gretty-runner-2.0.0.jar:na]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) [groovy-2.4.11.jar:2.4.11]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) [groovy-2.4.11.jar:2.4.11]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) [groovy-2.4.11.jar:2.4.11]
        at org.akhikhl.gretty.Runner.run(Runner.groovy:117) [gretty-runner-2.0.0.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_112]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_112]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_112]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_112]
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210) [groovy-2.4.11.jar:2.4.11]
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:71) [groovy-2.4.11.jar:2.4.11]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) [groovy-2.4.11.jar:2.4.11]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) [groovy-2.4.11.jar:2.4.11]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117) [groovy-2.4.11.jar:2.4.11]
        at org.akhikhl.gretty.Runner.main(Runner.groovy:44) [gretty-runner-2.0.0.jar:na]
Caused by: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for com.netflix.archaius.api.Config was bound.
  while locating com.netflix.archaius.api.Config
    for the 1st parameter of com.netflix.archaius.ConfigProxyFactory.<init>(ConfigProxyFactory.java:108)
  while locating com.netflix.archaius.ConfigProxyFactory
    for the 1st parameter of com.netflix.runtime.health.guice.HealthModule$InternalHealthModule.healthConfiguration(HealthModule.java:83)
  at com.netflix.runtime.health.guice.HealthModule$InternalHealthModule.healthConfiguration(HealthModule.java:83) (via modules: com.google.inject.util.Modules$CombinedModule -> com.netflix.florida.startup.FloridaModule -> com.netflix.florida.startup.FloridaModule$1 -> com.netflix.runtime.health.guice.HealthModule$InternalHealthModule)

2) No implementation for com.netflix.archaius.api.Decoder was bound.
  while locating com.netflix.archaius.api.Decoder
    for the 2nd parameter of com.netflix.archaius.ConfigProxyFactory.<init>(ConfigProxyFactory.java:108)
  while locating com.netflix.archaius.ConfigProxyFactory
    for the 1st parameter of com.netflix.runtime.health.guice.HealthModule$InternalHealthModule.healthConfiguration(HealthModule.java:83)
  at com.netflix.runtime.health.guice.HealthModule$InternalHealthModule.healthConfiguration(HealthModule.java:83) (via modules: com.google.inject.util.Modules$CombinedModule -> com.netflix.florida.startup.FloridaModule -> com.netflix.florida.startup.FloridaModule$1 -> com.netflix.runtime.health.guice.HealthModule$InternalHealthModule)

3) No implementation for com.netflix.archaius.api.PropertyFactory was bound.
  while locating com.netflix.archaius.api.PropertyFactory
    for the 3rd parameter of com.netflix.archaius.ConfigProxyFactory.<init>(ConfigProxyFactory.java:108)
  while locating com.netflix.archaius.ConfigProxyFactory
    for the 1st parameter of com.netflix.runtime.health.guice.HealthModule$InternalHealthModule.healthConfiguration(HealthModule.java:83)
  at com.netflix.runtime.health.guice.HealthModule$InternalHealthModule.healthConfiguration(HealthModule.java:83) (via modules: com.google.inject.util.Modules$CombinedModule -> com.netflix.florida.startup.FloridaModule -> com.netflix.florida.startup.FloridaModule$1 -> com.netflix.runtime.health.guice.HealthModule$InternalHealthModule)

4) No implementation for com.netflix.nfsidecar.local.ICredential annotated with @com.google.inject.name.Named(value=localroleassumption) was bound.
  while locating com.netflix.nfsidecar.local.ICredential annotated with @com.google.inject.name.Named(value=localroleassumption)
    for the 2nd parameter of com.netflix.nfsidecar.local.LocalMembership.<init>(LocalMembership.java:64)
  at com.netflix.florida.startup.FloridaModule.configure(FloridaModule.java:96) (via modules: com.google.inject.util.Modules$CombinedModule -> com.netflix.florida.startup.FloridaModule)

5) A binding to com.netflix.dynomitemanager.config.FloridaConfig was already configured at com.netflix.florida.startup.FloridaModule.configure(FloridaModule.java:100) (via modules: com.google.inject.util.Modules$CombinedModule -> com.netflix.florida.startup.FloridaModule).
  at com.netflix.florida.startup.FloridaModule.getFloridaConfig(FloridaModule.java:131) (via modules: com.google.inject.util.Modules$CombinedModule -> com.netflix.florida.startup.FloridaModule)

5 errors
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470) ~[na:na]
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155) ~[na:na]
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107) ~[na:na]
        at com.google.inject.Guice.createInjector(Guice.java:99) ~[na:na]
        at com.google.inject.Guice.createInjector(Guice.java:84) ~[na:na]
        at com.netflix.governator.LifecycleInjectorCreator.createInjector(LifecycleInjectorCreator.java:100) ~[na:na]
        at com.netflix.governator.LifecycleInjectorCreator.createInjector(LifecycleInjectorCreator.java:38) ~[na:na]
        at com.netflix.governator.InjectorBuilder.createInjector(InjectorBuilder.java:209) ~[na:na]
        at com.netflix.governator.InjectorBuilder.createInjector(InjectorBuilder.java:230) ~[na:na]
        at com.netflix.florida.startup.Florida.createInjector(Florida.java:45) ~[na:na]
        at com.netflix.governator.guice.servlet.GovernatorServletContainerInitializer$1.createInjector(GovernatorServletContainerInitializer.java:29) ~[na:na]
        at com.netflix.governator.guice.servlet.GovernatorServletContextListener.getInjector(GovernatorServletContextListener.java:107) ~[na:na]
        ... 53 common frames omitted
15:52:59 INFO  Jetty 9.2.22.v20170606 started and listening on port 8080
15:52:59 INFO   runs at:
15:52:59 INFO    http://localhost:8080/
Press any key to stop the server.
<============-> 94% EXECUTING
`
Thanks.

**Comment by ipapapa** [comment]
@sikkaka what is the issue you are seeing after you resolved the bindings problem?

**Comment by PavanNemala** [comment]
> I resolved this issue by binding them with their implementations. Still i do no how to make it work for local dc.

Hi, What files you have changed for solving this error

**Comment by ipapapa** [comment]
The files to add are probably mentioned in the Stacktrace as `no implementation is bound`.
