### ISSUE TITLE
Error: No implementation for com.netflix.archaius.api.Config was bound

### ISSUE THREAD

**Issue by opendedup** [Netflix/dynomite-manager#84]
When trying to run dynomite manager locally getting the following error:

21:56:30 WARN  Failed startup of context o.a.g.JettyWebAppContext@4b14918a{/,file:/root/dynomite-manager/dynomitemanager-web/build/inplaceWebapp/,STARTING}
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Failed to create injector

1 error
        at com.netflix.governator.guice.servlet.GovernatorServletContextListener.getInjector(GovernatorServletContextListener.java:111) ~[na:na]
        at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:47) ~[na:na]
        at com.netflix.governator.guice.servlet.GovernatorServletContextListener.contextInitialized(GovernatorServletContextListener.java:86) ~[na:na]
        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:800) ~[jetty-server-9.2.22.v20170606.jar:9.2.22.v20170606]
        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:444) ~[jetty-servlet-9.2.22.v20170606.jar:9.2.22.v20170606]
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:791) ~[jetty-server-9.2.22.v20170606.jar:9.2.22.v20170606]
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:294) ~[jetty-servlet-9.2.22.v20170606.jar:9.2.22.v20170606]
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349) ~[jetty-webapp-9.2.22.v20170606.jar:9.2.22.v20170606]
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342) ~[jetty-webapp-9.2.22.v20170606.jar:9.2.22.v20170606]
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741) ~[jetty-server-9.2.22.v20170606.jar:9.2.22.v20170606]
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505) ~[jetty-webapp-9.2.22.v20170606.jar:9.2.22.v20170606]
        at org.akhikhl.gretty.JettyWebAppContext.super$10$doStart(JettyWebAppContext.groovy) [gretty-runner-jetty9-2.0.0.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_144]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_144]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_144]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_144]
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93) [groovy-2.4.11.jar:2.4.11]
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325) [groovy-2.4.11.jar:2.4.11]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213) [groovy-2.4.11.jar:2.4.11]
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:132) [groovy-2.4.11.jar:2.4.11]
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:152) [groovy-2.4.11.jar:2.4.11]
        at org.akhikhl.gretty.JettyWebAppContext.doStart(JettyWebAppContext.groovy:44) [gretty-runner-jetty9-2.0.0.jar:na]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.2.22.v20170606.jar:9.2.22.v20170606]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132) [jetty-util-9.2.22.v20170606.jar:9.2.22.v20170606]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114) [jetty-util-9.2.22.v20170606.jar:9.2.22.v20170606]
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61) [jetty-server-9.2.22.v20170606.jar:9.2.22.v20170606]
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:163) [jetty-server-9.2.22.v20170606.jar:9.2.22.v20170606]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.2.22.v20170606.jar:9.2.22.v20170606]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132) [jetty-util-9.2.22.v20170606.jar:9.2.22.v20170606]
        at org.eclipse.jetty.server.Server.start(Server.java:387) [jetty-server-9.2.22.v20170606.jar:9.2.22.v20170606]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114) [jetty-util-9.2.22.v20170606.jar:9.2.22.v20170606]
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61) [jetty-server-9.2.22.v20170606.jar:9.2.22.v20170606]
        at org.eclipse.jetty.server.Server.doStart(Server.java:354) [jetty-server-9.2.22.v20170606.jar:9.2.22.v20170606]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.2.22.v20170606.jar:9.2.22.v20170606]
        at org.eclipse.jetty.util.component.LifeCycle$start$0.call(Unknown Source) [jetty-util-9.2.22.v20170606.jar:9.2.22.v20170606]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) [groovy-2.4.11.jar:2.4.11]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) [groovy-2.4.11.jar:2.4.11]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117) [groovy-2.4.11.jar:2.4.11]
        at org.akhikhl.gretty.JettyServerManager.startServer(JettyServerManager.groovy:45) [gretty-runner-jetty-2.0.0.jar:na]
        at org.akhikhl.gretty.ServerManager$startServer$0.call(Unknown Source) [gretty-runner-2.0.0.jar:na]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) [groovy-2.4.11.jar:2.4.11]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) [groovy-2.4.11.jar:2.4.11]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) [groovy-2.4.11.jar:2.4.11]
        at org.akhikhl.gretty.Runner.run(Runner.groovy:117) [gretty-runner-2.0.0.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_144]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_144]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_144]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_144]
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210) [groovy-2.4.11.jar:2.4.11]
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:71) [groovy-2.4.11.jar:2.4.11]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) [groovy-2.4.11.jar:2.4.11]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) [groovy-2.4.11.jar:2.4.11]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117) [groovy-2.4.11.jar:2.4.11]
        at org.akhikhl.gretty.Runner.main(Runner.groovy:44) [gretty-runner-2.0.0.jar:na]
Caused by: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for com.netflix.archaius.api.Config was bound.
  while locating com.netflix.archaius.api.Config
    for the 1st parameter of com.netflix.archaius.ConfigProxyFactory.<init>(ConfigProxyFactory.java:108)
  while locating com.netflix.archaius.ConfigProxyFactory
    for the 1st parameter of com.netflix.runtime.health.guice.HealthModule$InternalHealthModule.healthConfiguration(HealthModule.java:83)
  at com.netflix.runtime.health.guice.HealthModule$InternalHealthModule.healthConfiguration(HealthModule.java:83) (via modules: com.google.inject.util.Modules$CombinedModule -> com.netflix.florida.startup.FloridaModule -> com.netflix.florida.startup.FloridaModule$1 -> com.netflix.runtime.health.guice.HealthModule$InternalHealthModule)

2) No implementation for com.netflix.archaius.api.Decoder was bound.
  while locating com.netflix.archaius.api.Decoder
    for the 2nd parameter of com.netflix.archaius.ConfigProxyFactory.<init>(ConfigProxyFactory.java:108)
  while locating com.netflix.archaius.ConfigProxyFactory
    for the 1st parameter of com.netflix.runtime.health.guice.HealthModule$InternalHealthModule.healthConfiguration(HealthModule.java:83)
  at com.netflix.runtime.health.guice.HealthModule$InternalHealthModule.healthConfiguration(HealthModule.java:83) (via modules: com.google.inject.util.Modules$CombinedModule -> com.netflix.florida.startup.FloridaModule -> com.netflix.florida.startup.FloridaModule$1 -> com.netflix.runtime.health.guice.HealthModule$InternalHealthModule)

3) No implementation for com.netflix.archaius.api.PropertyFactory was bound.
  while locating com.netflix.archaius.api.PropertyFactory
    for the 3rd parameter of com.netflix.archaius.ConfigProxyFactory.<init>(ConfigProxyFactory.java:108)
  while locating com.netflix.archaius.ConfigProxyFactory
    for the 1st parameter of com.netflix.runtime.health.guice.HealthModule$InternalHealthModule.healthConfiguration(HealthModule.java:83)
  at com.netflix.runtime.health.guice.HealthModule$InternalHealthModule.healthConfiguration(HealthModule.java:83) (via modules: com.google.inject.util.Modules$CombinedModule -> com.netflix.florida.startup.FloridaModule -> com.netflix.florida.startup.FloridaModule$1 -> com.netflix.runtime.health.guice.HealthModule$InternalHealthModule)

3 errors
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470) ~[na:na]
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155) ~[na:na]
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107) ~[na:na]
        at com.google.inject.Guice.createInjector(Guice.java:99) ~[na:na]
        at com.google.inject.Guice.createInjector(Guice.java:84) ~[na:na]
        at com.netflix.governator.LifecycleInjectorCreator.createInjector(LifecycleInjectorCreator.java:100) ~[na:na]
        at com.netflix.governator.LifecycleInjectorCreator.createInjector(LifecycleInjectorCreator.java:38) ~[na:na]
        at com.netflix.governator.InjectorBuilder.createInjector(InjectorBuilder.java:209) ~[na:na]
        at com.netflix.governator.InjectorBuilder.createInjector(InjectorBuilder.java:230) ~[na:na]
        at com.netflix.florida.startup.Florida.createInjector(Florida.java:44) ~[na:na]
        at com.netflix.governator.guice.servlet.GovernatorServletContainerInitializer$1.createInjector(GovernatorServletContainerInitializer.java:29) ~[na:na]
        at com.netflix.governator.guice.servlet.GovernatorServletContextListener.getInjector(GovernatorServletContextListener.java:107) ~[na:na]
        ... 53 common frames omitted

**Comment by muxalko** [comment]
HI,
The same issue here:(
I believe, it is because we need to disable AWS stuff like is described in laptop.properties file:
```
# Do not try to register with discovery since we don't want others to discover our laptop.
netflix.discovery.registration.enabled=false
# Since we are not on AWS we don't have an instance ID and
# we don't want Eureka to check for that and fail initialization.
netflix.appinfo.validateInstanceId=false
# Since we are not in AWS let's not make a call to EC2 to ask for EC2 node specific info.
netflix.appinfo.doNotInitWithAmazonInfo=true

netflix.atlas.plugin.enabled=false

# These settings are required to prevent AtlasMainPoller NullPointerException when running locally
netflix.atlas.plugin.sendToEpic=false
epic.plugin.enabled=false

## Application info
netflix.appinfo.statusPageUrlPath=/REST/v1/admin/Status
netflix.appinfo.homePageUrlPath=/REST/v1/admin/Status
netflix.appinfo.healthCheckUrlPath=/healthcheck
netflix.appinfo.port=8080

# Needed for running locally behind VPN
swagger.hostname=localhost

governator.jetty.embedded.port=${netflix.appinfo.port}
```

Do one need to run jetty with some special flag/params ?

Thanks,
Michael

**Comment by ipapapa** [comment]
I am sorry for my delay to handle it. Here is the fix: https://github.com/Netflix/dynomite-manager/pull/87
